// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuUsSTrOnOauYvrDIFW9W_RvMaZ7A5gDw',
    appId: '1:81010658776:android:a84d2d198e781b54ce36ad',
    messagingSenderId: '81010658776',
    projectId: 'dash-forkobo',
    storageBucket: 'dash-forkobo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8kJcgUwEF3fr8_heoL3_n5tC9KgmwIJw',
    appId: '1:81010658776:ios:618b9aa9be60eab0ce36ad',
    messagingSenderId: '81010658776',
    projectId: 'dash-forkobo',
    storageBucket: 'dash-forkobo.firebasestorage.app',
    androidClientId: '81010658776-ehit8a2ke5baqvima2hqh4r44lnv4eaf.apps.googleusercontent.com',
    iosClientId: '81010658776-h1jfd9ueo8u69h16utdl069m8om5o9a8.apps.googleusercontent.com',
    iosBundleId: 'com.forkobo.merchant',
  );

}