import 'package:flutter/foundation.dart';

String get emptyAssetImage => 'assets/png/empty.png';
String get localUser => 'local-users-$kDebugMode';

//Hive boxes
String get settingsBoxName => 'app_settings_$kDebugMode';

class PrefKeys {
  static String get showWalkThru => 'show-walkthrough-screen';
  static String get userLoggedInToken => 'token_$kDebugMode';
}

String get currency => 'USD';

List<String> get deleveryCountries => [
  'Algeria',
  'Andorra',
  'Angola',
  'Argentina',
  'Australia',
  'Austria',
  'Belgium',
  'Bolivia',
  'Botswana',
  'Brazil',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Ecuador',
  'Egypt',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Finland',
  'France',
  'French Guiana',
  'Gabon',
  'Germany',
  'Ghana',
  'Greece',
  'Guinea',
  'Guyana',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Ireland',
  'Italy',
  'Japan',
  'Kenya',
  'Latvia',
  'Lesotho',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Malta',
  'Mali',
  'Mauritius',
  'Mexico',
  'Monaco',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Netherlands',
  'New Zealand',
  'Niger',
  'Nigeria',
  'Norway',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Republic of the Congo',
  'Romania',
  'Rwanda',
  'San Marino',
  'Senegal',
  'Seychelles',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Taiwan',
  'Tanzania',
  'Thailand',
  'Tunisia',
  'Turkey',
  'Uganda',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Zambia',
  'Zimbabwe',
];
