-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgEM+kCZOumnj+9GeX
xnk7Auh8f2J/w2ypBFwCgI3fc6+gCgYIKoZIzj0DAQehRANCAAT4GED2BNlhlheL
qEgC8mqNIamdwshQDCRSNIi7G/s7WfGFBaR8WYNCgXJMylgKOrkooJ/zEPYI2IRW
WSchdnwd
-----END PRIVATE KEY-----